### ISSUE TITLE
Allow the use of plain MobX stores as well?

### ISSUE THREAD

**Issue by theshire-io** [umijs/umi-plugin-mobx-state-tree#3]
Is there a way to have plain MobX stores as well?

I added this on the stores folder and got an error.

```
import React from "react";
import { observable, action } from "mobx";

class Foo {
  @observable test = 1;

  @action.bound
  plus() {
    this.test = this.test + 1;
  }
}

export default Foo;
```

```
Error: [mobx-state-tree] expected a mobx-state-tree type as first argument, got class Foo { constructor() { (0, _initializerDefineProperty2.default)(this, "test", _descriptor, this); } plus() { this.test = this.test + 1; } } instead
```

CodeSandbox: https://codesandbox.io/s/jjv6vq6mvy

**Comment by xiaohuoni** [comment]
the first argument must mobx-state-tree type，you can use the “types.model” 
```
import { types } from "mobx-state-tree";

@types.model
class Foo {
  @observable test = 1;

  @action.bound
  plus() {
    this.test = this.test + 1;
  }
}

export default Foo;
```

CodeSandbox:https://codesandbox.io/s/5kxrnpj3rp

**Comment by theshire-io** [comment]
Thank you, that doesn't throw an error but it doesn't behave as a mobx store any more. In retrospect, my suggestion does not seem to be on the right track. Thanks again!

**Comment by xiaohuoni** [comment]
what is “behave as a mobx store ”？

**Comment by theshire-io** [comment]
@xiaohuoni 

```
@types.model
class Foo {
  @observable test = 1;
}
```
```
render() {
  return() {
    <div>{this.props.stores.foo.test}</div>
  }
}
```

^ `NaN` instead of `1`.

https://codesandbox.io/s/kk1vk30z6r

I think that in order to work it needs to not be part of `RootStore` but of another root store, for example `MobxStore`, without the @types decoration. MST is fantastic but for some trivial state management (things like `isSidebarVisible`) having plain MobX stores is beneficial. It could be that the files found on `stores` get loaded into MST's `RootStore` and the files found on (e.g.) `mobxstores` get loaded into `MobxStore`, with `MobxStore` being something like:

```
stores; // The matching stores we found on the file system

export default class MobxSore {
  constructor() {
    stores.forEach(store => {
      this.[`${store.name}`]= new store.class(this); // Passing this so that each store can reference root and the rest of them, if wanted.
    })  
  }
}
```

Perhaps it makes sense to be a separate plugin, perhaps it makes sense to be on a single plugin (since I think many people use a mixture of both MST and plain stores).

**Comment by xiaohuoni** [comment]
@theshire-io Thank you for your guidance.

**Comment by xiaohuoni** [comment]
I don't understand，Why does 'foo' have no initdata and "get set"?
<img width="375" alt="wx20181019-153943 2x" src="https://user-images.githubusercontent.com/11746742/47204160-3b2ac480-d3b5-11e8-86bb-ccb7a6537d9b.png">

**Comment by theshire-io** [comment]
My guess is that since `RootStore.create` expects an MST type of store, things don't work properly if a proper instance isn't passed to it.
