### ISSUE TITLE
需要兼容 IE11, 报mobx5的错误

### ISSUE THREAD

**Issue by zmayor** [umijs/umi-plugin-mobx-state-tree#7]
因为需要兼容老一点的浏览器, 我把我安装的mobx降到了mobx4.7, 但是还是报错, 然后我全局搜索了后发现您的插件里面使用了mobx 5, 我不知道怎么修改为使用我自己装的mobx. 或者能否加个选项来选择使用mobx4还是mobx5呢?

**Comment by zmayor** [comment]
这个库内部关联了mobx我还需要安装mobx吗?

**Comment by xiaohuoni** [comment]
ie11是什么问题，已经安装应该不要安装了吧？你可以试试。
然后你可以通过， `resolutions` 指定需要的包的版本

**Comment by zmayor** [comment]
https://github.com/mobxjs/mobx/blob/master/README.md#browser-support
mobx5基于proxy啊，然后就不支持ie11了

**Comment by xiaohuoni** [comment]
你试试使用 resolutions 指定需要的包的版本

**Comment by zmayor** [comment]
请问这个是在什么地方配置呢，好像不是umi的配置

**Comment by zmayor** [comment]
https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

好吧，应该是这个

**Comment by xiaohuoni** [comment]
👍
