### ISSUE TITLE
能支持umi3吗 谢谢

### ISSUE THREAD

**Issue by ghost** [umijs/umi-plugin-mobx-state-tree#8]

**Comment by xiaohuoni** [comment]
应该没什么问题。我找时间处理下。

**Comment by zmayor** [comment]
还会支持吗...

**Comment by xiaohuoni** [comment]
@stfenjobs @zmayor cc

https://github.com/umijs/umi-plugin-mobx-state-tree/commit/cb0f9cc711b7cb2364554b4269f93b5be0bf3ebe
我在这里更新到了umi@3。项目中升级步骤如下。
### 升级插件版本
```
"umi-plugin-mobx-state-tree": "@3.0.0-beta.2"
```
### 修改插件配置
```diff
 export default {
-  plugins: [
-    [
-      "umi-plugin-mobx-state-tree",
-      {
-        exclude: [/^\$/] //这里是以$开头的stores不会被引用
-      }
-    ]
-  ]
+  mobx: {
+    exclude: [/^\$/] //这里是以$开头的stores不会被引用
+  }
 };
```
### 将页面级别的stores移到全局 src/stores 
因为现在直接使用文件名作为 stores 的 namespace 散落在各个文件夹下，反而更难维护。

**Comment by qinhuaihe** [comment]
谢谢大佬[磕头]

**Comment by qinhuaihe** [comment]
```
将页面级别的stores移到全局 src/stores
因为现在直接使用文件名作为 stores 的 namespace 散落在各个文件夹下，反而更难维护。
```
这个是说不支持页面级别的store了?

**Comment by xiaohuoni** [comment]
@zmayor 不支持的，你看看。https://github.com/umijs/umi-plugin-mobx-state-tree/blob/cb0f9cc711b7cb2364554b4269f93b5be0bf3ebe/src/index.js#L74
因为补上这个逻辑，也会有同名冲突问题。

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-plugin-mobx-state-tree/issues/6

**Comment by qinhuaihe** [comment]
但是在umi2中是可以把页面的store放到页面文件夹下的stores文件夹中的, 因此不会有同名冲突
![image](https://user-images.githubusercontent.com/18019463/81462970-b565a880-91e8-11ea-8bc5-f763879cb920.png)
